import type { OperationsData } from '../types';
// DEVELOPMENT ONLY. No real customer data. Never imported by production data paths.
const sizes = [
  { name: 'Nhỏ', extra: 0 },
  { name: 'Vừa', extra: 5000 },
  { name: 'Lớn', extra: 10000 },
];
export const fixtures: OperationsData = {
  businessId: 'preview-business',
  branchId: 'preview-branch',
  menu: [
    {
      id: 'coffee-milk',
      name: 'Cà phê sữa',
      category: 'Cà phê',
      price: 35000,
      description: 'Cà phê đậm đà, sữa đặc',
      sizes,
    },
    {
      id: 'coffee-black',
      name: 'Cà phê đen',
      category: 'Cà phê',
      price: 30000,
      description: 'Hương vị cà phê nguyên bản',
      sizes,
    },
    {
      id: 'latte',
      name: 'Cà phê sữa tươi',
      category: 'Cà phê',
      price: 45000,
      description: 'Cà phê cùng sữa tươi mềm dịu',
      sizes,
    },
    {
      id: 'milk-tea',
      name: 'Trà sữa trân châu',
      category: 'Trà sữa',
      price: 45000,
      description: 'Trà thơm, trân châu dẻo',
      sizes,
    },
    {
      id: 'peach',
      name: 'Trà đào cam sả',
      category: 'Đồ uống',
      price: 40000,
      description: 'Đào, cam và hương sả',
      sizes,
    },
    {
      id: 'orange',
      name: 'Nước cam',
      category: 'Đồ uống',
      price: 40000,
      description: 'Vị cam tươi mát',
      sizes,
    },
    {
      id: 'sandwich',
      name: 'Bánh mì gà',
      category: 'Đồ ăn',
      price: 45000,
      description: 'Gà, rau xanh và bánh mì',
      sizes: [{ name: 'Tiêu chuẩn', extra: 0 }],
    },
    {
      id: 'cake',
      name: 'Bánh phô mai',
      category: 'Bánh',
      price: 38000,
      description: 'Phô mai mịn, đế bánh giòn',
      sizes: [{ name: 'Một phần', extra: 0 }],
    },
  ],
  tables: [
    { id: 't1', name: 'Bàn 01', area: 'Tầng 1', seats: 4, status: 'AVAILABLE', lines: [] },
    {
      id: 't2',
      name: 'Bàn 02',
      area: 'Tầng 1',
      seats: 4,
      status: 'OCCUPIED',
      guests: 2,
      openedAt: '2026-10-20T02:15:00Z',
      billId: 'MH-002',
      lines: [{ name: 'Cà phê sữa', quantity: 2, price: 35000 }],
    },
    {
      id: 't3',
      name: 'Bàn 03',
      area: 'Tầng 1',
      seats: 2,
      status: 'NEED_PAYMENT',
      guests: 2,
      openedAt: '2026-10-20T01:30:00Z',
      billId: 'MH-003',
      lines: [
        { name: 'Trà sữa trân châu', quantity: 2, price: 45000 },
        { name: 'Bánh phô mai', quantity: 1, price: 38000 },
      ],
    },
    { id: 't4', name: 'Bàn 04', area: 'Tầng 2', seats: 6, status: 'RESERVED', lines: [] },
    { id: 't5', name: 'Bàn 05', area: 'Tầng 2', seats: 4, status: 'CLEANING', lines: [] },
    { id: 't6', name: 'Bàn 06', area: 'Phòng VIP', seats: 8, status: 'AVAILABLE', lines: [] },
    { id: 't7', name: 'Bàn 07', area: 'Ngoài trời', seats: 4, status: 'AVAILABLE', lines: [] },
    {
      id: 't8',
      name: 'Bàn 08',
      area: 'Ngoài trời',
      seats: 2,
      status: 'OCCUPIED',
      guests: 1,
      openedAt: '2026-10-20T03:00:00Z',
      billId: 'MH-008',
      lines: [{ name: 'Nước cam', quantity: 1, price: 40000 }],
    },
  ],
  orders: [
    {
      id: 'MH-101',
      at: '2026-10-20T01:10:00Z',
      cashier: 'Thu ngân minh họa',
      cashierId: 'preview-user',
      branchId: 'preview-branch',
      type: 'Tại bàn',
      table: 'Bàn 01',
      total: 70000,
      status: 'PAID',
      payment: 'CASH',
      shiftId: 'shift-demo',
    },
    {
      id: 'MH-102',
      at: '2026-10-20T02:20:00Z',
      cashier: 'Thu ngân minh họa',
      cashierId: 'preview-user',
      branchId: 'preview-branch',
      type: 'Mang đi',
      table: '—',
      total: 90000,
      status: 'PAID',
      payment: 'BANK',
      shiftId: 'shift-demo',
    },
    {
      id: 'MH-103',
      at: '2026-10-20T03:15:00Z',
      cashier: 'Thu ngân minh họa',
      cashierId: 'preview-user',
      branchId: 'preview-branch',
      type: 'Tại bàn',
      table: 'Bàn 04',
      total: 45000,
      status: 'CANCELLED',
      payment: 'CASH',
      shiftId: 'shift-demo',
    },
    {
      id: 'MH-104',
      at: '2026-10-20T03:40:00Z',
      cashier: 'Thu ngân khác (minh họa)',
      cashierId: 'preview-other',
      branchId: 'preview-branch',
      type: 'Mang đi',
      table: '—',
      total: 38000,
      status: 'PAID',
      payment: 'CASH',
      shiftId: 'shift-other',
    },
    {
      id: 'MH-105',
      at: '2026-10-19T03:40:00Z',
      cashier: 'Thu ngân minh họa',
      cashierId: 'preview-user',
      branchId: 'preview-branch',
      type: 'Mang đi',
      table: '—',
      total: 30000,
      status: 'PAID',
      payment: 'CASH',
      shiftId: 'shift-previous',
    },
  ],
  shift: {
    id: 'shift-demo',
    start: '2026-10-20T01:00:00Z',
    asOf: '2026-10-20T04:30:00Z',
    status: 'Đang mở',
  },
};
