import type { ManagerData } from '../types';
// Isolated development dataset. No real customer or production analytics.
export const managerFixtures: ManagerData = {
  businessId: 'preview-business',
  branchId: 'preview-branch',
  asOf: '2026-10-20T11:00:00+07:00',
  ingredients: [
    {
      id: 'bean',
      name: 'Cà phê hạt',
      category: 'Cà phê',
      unit: 'g',
      stock: 800,
      minimum: 1000,
      expiry: '2026-12-20',
      costPerUnit: 250,
    },
    {
      id: 'milk',
      name: 'Sữa tươi',
      category: 'Sữa',
      unit: 'ml',
      stock: 9000,
      minimum: 3000,
      expiry: '2026-10-22',
      costPerUnit: 35,
    },
    {
      id: 'condensed',
      name: 'Sữa đặc',
      category: 'Sữa',
      unit: 'g',
      stock: 2000,
      minimum: 500,
      expiry: '2027-01-20',
      costPerUnit: 55,
    },
    {
      id: 'matcha',
      name: 'Bột trà xanh',
      category: 'Bột',
      unit: 'g',
      stock: 700,
      minimum: 200,
      expiry: '2027-01-01',
      costPerUnit: 1200,
    },
    {
      id: 'cocoa',
      name: 'Bột ca cao',
      category: 'Bột',
      unit: 'g',
      stock: 850,
      minimum: 200,
      expiry: '2027-02-01',
      costPerUnit: 350,
    },
    {
      id: 'vanilla',
      name: 'Siro vani',
      category: 'Siro',
      unit: 'ml',
      stock: 0,
      minimum: 300,
      expiry: null,
      costPerUnit: 150,
    },
    {
      id: 'peach',
      name: 'Siro đào',
      category: 'Siro',
      unit: 'ml',
      stock: 1200,
      minimum: 300,
      expiry: '2026-12-01',
      costPerUnit: 120,
    },
    {
      id: 'pearl',
      name: 'Trân châu',
      category: 'Topping',
      unit: 'g',
      stock: 2500,
      minimum: 700,
      expiry: '2026-11-01',
      costPerUnit: 45,
    },
    {
      id: 'orange',
      name: 'Cam tươi',
      category: 'Trái cây',
      unit: 'g',
      stock: 6000,
      minimum: 2000,
      expiry: '2026-10-27',
      costPerUnit: 25,
    },
    {
      id: 'lemon',
      name: 'Chanh tươi',
      category: 'Trái cây',
      unit: 'g',
      stock: 2500,
      minimum: 500,
      expiry: '2026-10-28',
      costPerUnit: 30,
    },
    {
      id: 'flour',
      name: 'Bột mì',
      category: 'Nguyên liệu làm bánh',
      unit: 'g',
      stock: 5000,
      minimum: 1000,
      expiry: '2027-03-01',
      costPerUnit: 20,
    },
    {
      id: 'butter',
      name: 'Bơ lạt',
      category: 'Nguyên liệu làm bánh',
      unit: 'g',
      stock: 2000,
      minimum: 500,
      expiry: '2026-11-20',
      costPerUnit: 180,
    },
  ],
  days: [
    { date: '2026-10-14', revenue: 3250000, orders: 68, foodCost: 1050000 },
    { date: '2026-10-15', revenue: 3800000, orders: 80, foodCost: 1220000 },
    { date: '2026-10-16', revenue: 3500000, orders: 72, foodCost: 1150000 },
    { date: '2026-10-17', revenue: 5100000, orders: 105, foodCost: 1670000 },
    { date: '2026-10-18', revenue: 5500000, orders: 114, foodCost: 1800000 },
    { date: '2026-10-19', revenue: 4050000, orders: 87, foodCost: 1320000 },
    { date: '2026-10-20', revenue: 1660000, orders: 40, foodCost: 373200 },
  ],
  hours: [
    { hour: '07:00', orders: 5, revenue: 190000 },
    { hour: '08:00', orders: 12, revenue: 500000 },
    { hour: '09:00', orders: 15, revenue: 630000 },
    { hour: '10:00', orders: 8, revenue: 340000 },
  ],
  recipes: [
    {
      id: 'coffee-milk',
      name: 'Cà phê sữa',
      category: 'Cà phê',
      price: 35000,
      ingredients: [
        { ingredientId: 'bean', quantity: 20 },
        { ingredientId: 'condensed', quantity: 30 },
      ],
      modifiers: [
        { name: 'Thêm sữa đặc', ingredientId: 'condensed', quantity: 15, priceExtra: 5000 },
      ],
    },
    {
      id: 'latte',
      name: 'Cà phê sữa tươi',
      category: 'Cà phê',
      price: 45000,
      ingredients: [
        { ingredientId: 'bean', quantity: 18 },
        { ingredientId: 'milk', quantity: 180 },
      ],
      modifiers: [{ name: 'Cỡ lớn', ingredientId: 'milk', quantity: 60, priceExtra: 10000 }],
    },
    {
      id: 'matcha-milk',
      name: 'Trà xanh sữa tươi',
      category: 'Đồ uống',
      price: 50000,
      ingredients: [
        { ingredientId: 'matcha', quantity: 5 },
        { ingredientId: 'milk', quantity: 180 },
        { ingredientId: 'condensed', quantity: 20 },
      ],
      modifiers: [],
    },
    {
      id: 'orange-juice',
      name: 'Nước cam',
      category: 'Đồ uống',
      price: 40000,
      ingredients: [{ ingredientId: 'orange', quantity: 300 }],
      modifiers: [],
    },
  ],
  bestSellers: [
    { recipeId: 'coffee-milk', quantity: 16 },
    { recipeId: 'latte', quantity: 12 },
    { recipeId: 'matcha-milk', quantity: 8 },
    { recipeId: 'orange-juice', quantity: 4 },
  ],
  transactions: [
    {
      id: 'GD-MH-01',
      type: 'IN',
      ingredientId: 'milk',
      quantity: 6000,
      supplier: 'Nhà cung cấp minh họa',
      expiry: '2026-10-22',
      note: 'Bổ sung nguyên liệu đầu ca (minh họa)',
      at: '2026-10-20T00:15:00Z',
    },
    {
      id: 'GD-MH-02',
      type: 'OUT',
      ingredientId: 'bean',
      quantity: 300,
      supplier: '',
      expiry: null,
      note: 'Chuyển nguyên liệu ra quầy (minh họa)',
      at: '2026-10-20T01:00:00Z',
    },
    {
      id: 'GD-MH-03',
      type: 'WASTE',
      ingredientId: 'orange',
      quantity: 200,
      supplier: '',
      expiry: null,
      note: 'Loại bỏ nguyên liệu hỏng (minh họa)',
      at: '2026-10-20T02:00:00Z',
    },
  ],
  alerts: [
    {
      id: 'alert-milk',
      category: 'NEAR_EXPIRY',
      ingredientId: 'milk',
      title: 'Sữa tươi sắp hết hạn',
      detail:
        'Lô sữa minh họa có hạn sử dụng ngày 22/10/2026. Kiểm tra lô và ưu tiên sử dụng phù hợp.',
      status: 'OPEN',
      at: '2026-10-20T00:00:00Z',
    },
    {
      id: 'alert-vanilla',
      category: 'OUT_OF_STOCK',
      ingredientId: 'vanilla',
      title: 'Siro vani đã hết hàng',
      detail: 'Tồn hiện tại bằng 0. Kiểm tra khả năng phục vụ các món có sử dụng siro vani.',
      status: 'OPEN',
      at: '2026-10-20T01:00:00Z',
    },
    {
      id: 'alert-bean',
      category: 'LOW_STOCK',
      ingredientId: 'bean',
      title: 'Cà phê hạt dưới mức tồn tối thiểu',
      detail: 'Còn 800 g so với mức tối thiểu 1.000 g. Cân nhắc bổ sung nguyên liệu.',
      status: 'IN_PROGRESS',
      at: '2026-10-20T02:00:00Z',
    },
    {
      id: 'alert-flour',
      category: 'DISCREPANCY',
      ingredientId: 'flour',
      title: 'Đã đối chiếu tồn kho bột mì',
      detail:
        'Tình huống minh họa chênh lệch tồn kho đã được đối chiếu. Không phải kết quả kiểm kê thực tế.',
      status: 'RESOLVED',
      at: '2026-10-19T03:00:00Z',
    },
  ],
  staff: [
    {
      id: 'staff-demo-1',
      name: 'Nhân viên mẫu 01',
      email: 'nhanvien01@example.test',
      role: 'STAFF',
      shift: '07:00 – 15:00',
      lastLogin: '2026-10-20T00:00:00Z',
      status: 'ACTIVE',
    },
    {
      id: 'staff-demo-2',
      name: 'Nhân viên mẫu 02',
      email: 'nhanvien02@example.test',
      role: 'STAFF',
      shift: '15:00 – 23:00',
      lastLogin: '2026-10-19T08:00:00Z',
      status: 'ACTIVE',
    },
    {
      id: 'staff-demo-3',
      name: 'Nhân viên mẫu 03',
      email: 'nhanvien03@example.test',
      role: 'STAFF',
      shift: 'Chưa phân ca',
      lastLogin: null,
      status: 'INACTIVE',
    },
    {
      id: 'preview-user',
      name: 'Quản lý mẫu',
      email: 'quanly@example.test',
      role: 'MANAGER',
      shift: '07:00 – 15:00',
      lastLogin: '2026-10-20T00:00:00Z',
      status: 'ACTIVE',
    },
    {
      id: 'owner-demo',
      name: 'Chủ doanh nghiệp mẫu',
      email: 'chu@example.test',
      role: 'OWNER',
      shift: 'Không áp dụng',
      lastLogin: '2026-10-19T02:00:00Z',
      status: 'ACTIVE',
    },
  ],
};
